---
# tasks file for wordpress

- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no 
  tags:
    - download-wp

- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/srv/ copy=no 
  tags:
    - extract-wp

- name: Copy sample config file
  command: mv /srv/wordpress/wp-config-sample.php /srv/wordpress/wp-config.php creates=/srv/wordpress/wp-config.php
  tags:
    - copy-config